### ISSUE TITLE
trackLink does not pass options through.

### ISSUE THREAD

**Issue by attack** [segmentio/analytics.js#403] opened 2014-10-10 20:31 UTC
`track` takes `(event, properties, options, fn)` but `trackLink` only takes `(event, properties)`, so there is no way to pass through options.

It would be greatly appreciated if this attribute could be passed through.

**Comment by stevenmiller888** [comment] 2015-03-10 23:22
+1 @yields @sperand-io

**Comment by tcassanego** [comment] 2015-03-10 23:35
Definitely second it as well.  In the meantime, I've wrapped up the call to track in a click handler that sets a 300ms timeout and then changes pages.

**Comment by seantanly** [comment] 2016-09-05 09:28
👍 +1

**Comment by SeyZ** [comment] 2017-08-11 10:23
+1... we're now in 2017 :(

**Comment by heymanhn** [comment] 2017-11-10 01:02
+1

**Comment by f2prateek** [comment] 2017-11-22 06:30
Tracking internally https://segment.atlassian.net/browse/LIB-102

**Comment by f2prateek** [comment] 2017-11-24 22:49
The change will be in a.js-core, closing this as a duplicate of https://github.com/segmentio/analytics.js-core/issues/41.

**Closed by f2prateek** 2017-11-24 22:49 UTC
Labels: improvement
