### ISSUE TITLE
Uncaught TypeError: o.queue.push is not a function

### ISSUE THREAD

**Issue by aabilio** [segmentio/analytics.js#626] opened 2020-03-06 18:36 UTC
```
Uncaught TypeError: o.queue.push is not a function
    at analytics.min.js:8
    at u (analytics.min.js:2)
    at c (analytics.min.js:2)
    at i._reclaim (analytics.min.js:8)
    at analytics.min.js:8
    at analytics.min.js:8
```
I'm always getting this kind of error but I can't debug the reason.
Using the `debug` method  I can see that the requests its enqueued but never resolved. 

![Screenshot 2020-03-06 at 19 31 33](https://user-images.githubusercontent.com/664712/76112020-b0665c00-5fe1-11ea-9102-94cdaae0a944.png)

Only the first time the user access after a few days without accessing, the event is sent google analytics. Events are properly tracked in Segment debugger.

The integration was working properly until the beginning of the year and it has been failing for 2 months without any change in the integration. Has anyone had any similar issues?

**Comment by ykliao** [comment] 2020-03-25 13:11
Yes. I just started to experiment with Segment using javascript but ran into this issue too.  When I switched to the uncompressed version of analytics.js, the error messages looked like below, 

analytics.js:17055 Uncaught TypeError: our.queue.push is not a function
    at analytics.js:17055
    at arrayEach (analytics.js:3040)
    at each (analytics.js:3098)
    at Queue._reclaim (analytics.js:17054)
    at analytics.js:17012
    at analytics.js:17142

**Comment by ykliao** [comment] 2020-03-26 15:57
A bit more information. The version of analytics.js being used as of today is 
analytics.SNIPPET_VERSION = '4.1.0';

After a bit more investigation, it looks like somehow the type of  our.queue turned into string, resulting in the problem of calling .push() and .sort() functions on it. One possible workaround is to check the typeof our.queue to make sure it is an array, perhaps with Array.isArray before making these calls. I am however, not sure if that will still produce the right end results.

**Comment by ykliao** [comment] 2020-04-01 22:06
@aabilio , not sure if your issue is caused by the same thing as mine. My problem is related to a reference to prototype.js. The problem went away for me once prototype.js is removed from my project. HTH.

**Comment by aabilio** [comment] 2020-04-02 10:53
Thanks for the information @ykliao.
But we are not using prototype.js in our project.
Did you debug the root cause of the problem? It will be useful to depurate my error.
What I discovered is that the "array" that the script it's trying to push is stored in localStorage as '"[]"' instead of "[]". So when it's parsed from the localStorage it's converted to "[]", so it's a string, not an array, and the push error method is raised. But I don't know which part is writing the localStorage with the incorrect value. And if try to edit it, or remove it, it's instantly created again with the '"[]"' value. 🤔

**Comment by branthanna** [comment] 2020-07-10 22:33
I hit what appears to be the same issue. I tried to work up the most simple Visualforce page I could that trips the problem. See the code snippets below (where the includeScript pulls in the JavaScript generated by Segment). This appears to likely be a conflict between Salesforce's generated HTML/JavaScript and Segment's.  Segment suggested a few workaround possibilities for me - using a HTTP endpoint (requiring writing some Apex in the page controller) or using the pixel image on the page. I am going to investigate those options as I feel like if it is a conflict that this will only change if Salesforce or Segment make a change in their products.

If anyone has come up with a way to get around the issue while still using the Segment JavaScript approach I'm all ears though!!!

**this code does not log analytics**
<apex:page >
<apex:includeScript value="{!$Resource.H1Analytics}" />
        <apex:tabPanel>
        </apex:tabPanel>
</apex:page>
**This code does:**
<apex:page >
<apex:includeScript value="{!$Resource.H1Analytics}" />
</apex:page>

**Comment by pooyaj** [comment] 2020-07-17 16:28
Adding more info here, it seems that the source of issue is the use of non-native `JSON.stringify` in certain third party libraries. Some libraries override the `.toJSON` method of Arrays, Objects, etc. ( for compatibility with older browsers, and usually using `Prototype` library ). That  particular implementation adds extra double quotes around the stringified Arrays, which prevents converting Arrays between stringified/non-stringified version here. 

I'm going to close this for now, unless there specific reproduction steps.

**Closed by pooyaj** 2020-07-17 16:28 UTC
Labels: Bug, Status: triage needed

**Comment by branthanna** [comment] 2020-08-12 16:56
>>>I'm going to close this for now, unless there specific reproduction steps.

I posted specific, clear and simple reproduction steps above. Definitely a reproducible, consistent issue. I implemented a workaround (using a different interface to Segment) but it would be good to have a fix to this issue if some one can come up with one. Can we reopen this given it hasn't been solved?

**Comment by pooyaj** [comment] 2020-08-12 18:22
@branthanna our theory is that the issue is related to certain apps or libraries ( in your case VisualForce ) overriding `JSON.stringify`. The problem is we are not familiar with VisualForce or have access to a VisualForce environment to reproduce the issue. Happy to debug the issue further if there is an environment I can test the issue in ( either a live, publicly accessible website, or a codesandbox environment ).

**Comment by priyansh1161** [comment] 2020-10-19 13:30
+1 @pooyaj 
@branthanna 
I had the same issue, one of the libraries that I was using had `prototype.js` as a dependency which mutates the prototype of Array and adds a new function `toJSON` to the prototype of Array. 

To confirm if the issue is the same try typing `Array.prototype.toJSON` on the console, and you'll see this ( or similar ) function

```js
function() {
        var e = [];
        return this.each(function(t) {
            var i = Object.toJSON(t);
            Object.isUndefined(i) || e.push(i)
        }),
        "[" + e.join(", ") + "]"
    }
```

Now, it can be seen that this code is the culprit that causes issues with `JSON.stringify` and hence at times stores in localStorage as '"[]"' instead of "[]".

A hack to fix the issue ( that works, since ES5 JSON support is pretty much standard now ).

```js
delete Array.prototype.toJSON
```
Just add this line once prototype.js is loaded, This will reset the behavior of `JSON.stringify`. However, a word of caution, this might break some very very old code relying on this function particularly.
