### ISSUE TITLE
Cannot read property 'identify' of undefined

### ISSUE THREAD

**Issue by srpanwar-confluent** [segmentio/analytics.js#627] opened 2020-03-09 14:28 UTC
The said error is gets intermittently thrown. Relevant portion of the stack trace.

```{
              "function": "HTMLScriptElement.<anonymous>",
              "abs_path": "https://cdn.segment.com/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "module": "analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics",
              "filename": "/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "lineno": 11,
              "colno": 1486,
              "in_app": true
            },
            {
              "abs_path": "https://cdn.segment.com/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "module": "analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics",
              "in_app": true,
              "lineno": 8,
              "colno": 20167,
              "filename": "/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js"
            },
            {
              "function": "t.n.ready",
              "abs_path": "https://cdn.segment.com/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "module": "analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics",
              "filename": "/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "lineno": 1,
              "colno": 30409,
              "in_app": true
            },
            {
              "function": "t.o.emit",
              "abs_path": "https://cdn.segment.com/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "module": "analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics",
              "filename": "/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "lineno": 9,
              "colno": 3464,
              "in_app": true
            },
            {
              "function": "t.n",
              "abs_path": "https://cdn.segment.com/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "module": "analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics",
              "filename": "/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "lineno": 9,
              "colno": 2718,
              "in_app": true
            },
            {
              "function": "t.<anonymous>",
              "abs_path": "https://cdn.segment.com/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "module": "analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics",
              "filename": "/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "lineno": 8,
              "colno": 20167,
              "in_app": true
            },
            {
              "function": "t.n.flush",
              "abs_path": "https://cdn.segment.com/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "module": "analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics",
              "filename": "/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "lineno": 1,
              "colno": 29447,
              "in_app": true
            },
            {
              "function": "c",
              "abs_path": "https://cdn.segment.com/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "module": "analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics",
              "filename": "/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "lineno": 2,
              "colno": 4545,
              "in_app": true
            },
            {
              "function": "u",
              "abs_path": "https://cdn.segment.com/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "module": "analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics",
              "filename": "/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "lineno": 2,
              "colno": 4414,
              "in_app": true
            },
            {
              "abs_path": "https://cdn.segment.com/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "module": "analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics",
              "in_app": true,
              "lineno": 1,
              "colno": 29473,
              "filename": "/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js"
            },
            {
              "function": "t.r.identify",
              "abs_path": "https://cdn.segment.com/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "module": "analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics",
              "filename": "/analytics.js/v1/zUp9sNH3D26HFumahgmZN365gTFglSSf/analytics.min.js",
              "lineno": 3,
              "colno": 36378,
              "in_app": true
            }
```

**Comment by pooyaj** [comment] 2020-07-17 16:20
Closing this, as I cannot reproduce.

**Closed by pooyaj** 2020-07-17 16:20 UTC
Labels: Bug, Status: awaiting author response
